$(document).ready(function(){
    $("#premier").click(function(){
		$("#showdata1").fadeIn();
		$("#showdata2").hide();
		$("#showdata3").hide();
        $("showdata4").hide();
        $("showdata5").hide();
		$("#Eng").fadeIn(2000);
		$("#France").hide();
		$("#Spain").hide();
        $("#Germany").hide();
        $("#Italy").hide();
		
    });
	$("#laliga").click(function(){
		$("#showdata2").fadeIn();
		$("#showdata1").hide();
		$("#showdata3").hide();
		$("showdata4").hide();
        $("showdata5").hide();
        $("#Spain").fadeIn(2000);
		$("#Eng").hide();
		$("#France").hide();
        $("#Germany").hide();
        $("#Italy").hide();
		
    });
	$("#ligue1").click(function(){
		$("#showdata3").fadeIn();
		$("#showdata1").hide();
		$("#showdata2").hide();
		$("showdata4").hide();
        $("showdata5").hide();
        $("#France").fadeIn(2000);
		$("#Eng").hide();
		$("#Spain").hide();
        $("#Germany").hide();
        $("#Italy").hide();
    });
    $("#bundesliga").click(function(){
		$("#showdata1").hide();
		$("#showdata2").hide();
		$("#showdata3").hide();
		$("showdata4").fadeIn();
        $("showdata5").hide();
        $("#Eng").hide();
		$("#France").hide();
		$("#Spain").hide();
		$("#Germany").fadeIn(2000);
        $("#Italy").hide();
    });
     $("#seriaa").click(function(){
		$("#showdata1").hide();
		$("#showdata2").hide();
		$("#showdata3").hide();
		$("showdata4").hide();
        $("showdata5").fadeIn();
        $("#Eng").hide();
		$("#France").hide();
		$("#Spain").hide();
		$("#Germany").hide();
        $("#Italy").fadeIn(2000);
    });
});